In [19]:
'''
# CustomLayer
'''
import tensorflow as tf
tf.enable_eager_execution()
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
layer = tf.keras.layers.Dense(10,input_shape=(None,5)) # 10 dimension of output
# use a layer
layer(tf.zeros([10,5]))
# inspect layer variables
layer.variables

[<tf.Variable 'dense_11/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.15856671,  0.5142376 ,  0.3704372 , -0.2507851 ,  0.04521245,
         -0.5604258 ,  0.4002692 , -0.51249313, -0.1777617 , -0.25331175],
        [-0.13241309,  0.14858478,  0.26649827, -0.5820701 ,  0.28057575,
         -0.03742629,  0.50551397, -0.3235623 ,  0.27918398,  0.45734435],
        [-0.2870309 ,  0.12711102, -0.2515172 , -0.490287  ,  0.45290214,
         -0.14846158, -0.11887223,  0.01223415,  0.24653178, -0.5674909 ],
        [-0.5266123 ,  0.21707618,  0.33146155, -0.09039718,  0.61514896,
         -0.05334455, -0.17419147, -0.47648346,  0.05691552,  0.19374025],
        [-0.0146451 ,  0.13913119,  0.22121024,  0.33712864,  0.531426  ,
          0.09762484,  0.29149336, -0.42858574, -0.05251169, -0.27859262]],
       dtype=float32)>,
 <tf.Variable 'dense_11/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [14]:
layer.kernel

<tf.Variable 'dense_9/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.60317004,  0.29735106,  0.5525548 ,  0.26152492, -0.4012888 ,
        -0.45187783, -0.5508338 , -0.4672752 , -0.4507941 ,  0.5098825 ],
       [ 0.07211643,  0.5268138 ,  0.27953368,  0.43284398, -0.05539483,
         0.10875082,  0.2957375 , -0.5974245 , -0.21372658, -0.10345387],
       [ 0.50502557, -0.33884522, -0.11771595,  0.37420374,  0.28772563,
         0.58718604,  0.43105274,  0.31320894,  0.49767262, -0.5273149 ],
       [ 0.5096832 ,  0.27220172,  0.20525044, -0.55492187, -0.04032582,
        -0.18168706, -0.48612854, -0.18369406, -0.08028328, -0.36795416],
       [ 0.45442945,  0.2802015 ,  0.30973327, -0.27177784,  0.04215825,
        -0.6246181 ,  0.1935237 , -0.1799967 , -0.39873144, -0.4719061 ]],
      dtype=float32)>

In [15]:
layer.bias

<tf.Variable 'dense_9/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [47]:
# Implementing custom layer
# extending tf.keras.Layer class
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        print('b-check',input_shape)
        print(input_shape[-1],self.num_outputs)
        self.kernel = self.add_variable("kernel",shape=[int(input_shape[-1]),self.num_outputs])
        print('bb-check')
        
    def call(self,input):
        print('c-check')
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print('check')
print(layer(tf.zeros([10, 5])))
print('check')
print(layer.trainable_variables)

check
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(10, 5), dtype=float32)
b-check (10, 5)
5 10
bb-check
c-check
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
check
[<tf.Variable 'my_dense_layer_23/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.26174206,  0.1073103 ,  0.2815342 ,  0.16341156, -0.26420748,
         0.43810326,  0.22158045, -0.2293016 , -0.2158536 ,  0.46685797],
       [ 0.02323103,  0.44008547,  0.07808417, -0.27902144,  0.45709556,
         0.01620167, -0.4378807 ,  0.03620374,  0.1747

In [44]:
# Composing layer
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self,kernel_size,filters):
        super(ResnetIdentityBlock,self).__init__(name='')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1,(1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size,padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3,(1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self,input_tensor,training=False):
        print('v-check')
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)
# filters: Integer, the dimensionality of the output space (i.e. the number of output filters in the convolution).
block = ResnetIdentityBlock(1,[1,2,3])
print('check')
print(block(tf.zeros([1,2,3,3])))
print('check')
print([x.name for x in block.trainable_variables])


check
v-check
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
check
['resnet_identity_block_4/conv2d_12/kernel:0', 'resnet_identity_block_4/conv2d_12/bias:0', 'resnet_identity_block_4/batch_normalization_v1_12/gamma:0', 'resnet_identity_block_4/batch_normalization_v1_12/beta:0', 'resnet_identity_block_4/conv2d_13/kernel:0', 'resnet_identity_block_4/conv2d_13/bias:0', 'resnet_identity_block_4/batch_normalization_v1_13/gamma:0', 'resnet_identity_block_4/batch_normalization_v1_13/beta:0', 'resnet_identity_block_4/conv2d_14/kernel:0', 'resnet_identity_block_4/conv2d_14/bias:0', 'resnet_identity_block_4/batch_normalization_v1_14/gamma:0', 'resnet_identity_block_4/batch_normalization_v1_14/beta:0']


In [49]:
# !Sequential
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(2, 1, 
                                                      padding='same'),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(3, (1, 1)),
                               tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=1957, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>